### ISSUE TITLE
Guess Number | option2

### ISSUE THREAD

**Issue by akrish4** [akrish4/Guess_Number#2]
### User guesses the number that is assumed by computer
![image2](https://user-images.githubusercontent.com/61831021/102186700-ffc6aa80-3ed8-11eb-9c5c-7e0a1c4aef0f.PNG)

**Comment by abdallah1097** [comment]
May you clarify what is required? it seems like this feature is already implemented!

**Comment by akrish4** [comment]
@abdallah1097  yes this feature is implemented and this issue is created to get better  understanding of output and functioning.
